Feat/voting power purchase
Prometeus-Network/ignite-back-end pull request #88
Opened 2020-10-05 13:11 UTC by jonyroww

2020-10-05 15:05 UTC, Edgar-P-yan requested changes

2020-10-05 15:05 UTC, Edgar-P-yan commented on .env.example
> +VOTING_POWER_CONST=
VOTING_POWER_CONST -> PROM_TO_VOTING_POWER_RATIO
Просто стороний чел не понял бы, констант там хер пойми сколько)

2020-10-05 15:05 UTC, Edgar-P-yan commented on src/memezator/memezator.service.ts
> +        const votingPowerPurchase = await this.votingPowerPurchaseRepository.findOne({where: {userId: like.user.id}})
Нужно найти не просто одну запись, а сумму всех купленных в этот день (competitionStartDate) вотинг паверов, и этот квери нужны реализовать в репозитории, а не тут в коде)

2020-10-05 15:05 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +    @Cron('* 60 * * * *')
Это вообще работает?) И сколько это?

2020-10-05 15:05 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +      const transactions = await this.tokenExchangeService.getTransactions();
getTransactions - хер пойми какие именно транзакции возвращает. лучше getIncomingTokenTransfersToVotingPowerPurchaseAccount - или как-то так, типо входящие токен-трансферы  в счет покупки потинг павера

2020-10-05 15:05 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +        if (!transactionRecord){
Вот эта часть всегда не сработает, потому что пока что p2p транзы не синхронизируются. Я пока доделаю синхронизацию, тогда и будет это работать. А пока можно пускать и записывать покупки даже без записи в таблице transactions

2020-10-05 15:05 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +        const votingPowerPurchaseExist = await this.votingPowerPurchaseRepository.findOne({where: {txnId: transactionRecord.id}})
Эти проверки пока давай делать по хешу транзы, потому что айди транзы пока не будет

2020-10-05 15:05 UTC, Edgar-P-yan commented on src/transactions/transactions.controller.ts
> +    return this.transactionsService.refreshTransactions(param);
Это скоро уже не понадобится, можно пока закомментить, вместо этого делаем полную синхронизацию с переводами промов

2020-10-06 15:25 UTC, jonyroww commented on src/memezator/voting-power-purchase-cron.service.ts
> +    @Cron('* 60 * * * *')
Каждую 60-ю минуту получается, т.е. каждый час.)

2020-10-12 15:33 UTC, Edgar-P-yan requested changes

2020-10-12 15:33 UTC, Edgar-P-yan commented on src/migrations/1602505205168-voting-power-index-drop.ts
> +export class votingPowerIndexDrop1602505205168 implements MigrationInterface {
Давай просто удалить этот файл, все равно откатали

2020-10-12 15:33 UTC, Edgar-P-yan commented on src/migrations/1601648264714-transactions-txnHash-unique-index.ts
> +export class transactionsTxnHashUniqueIndex1601648264714 implements MigrationInterface {
Давай просто удалить этот файл, все равно откатали

2020-10-12 15:33 UTC, Edgar-P-yan commented on src/transactions/transactions.service.ts
> +  public async refreshTransactions(param: RefreshTransactionsRequest){
коменты удаляем

2020-10-12 15:33 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase.repository.ts
> +public async calculateVotingPowerForUser(userId: string){
return type

2020-10-12 15:33 UTC, Edgar-P-yan commented on src/transactions/types/requests/RefreshTransactionsRequest.ts
> +export class RefreshTransactionsRequest {
Это тоже уже не нужно)

2020-10-12 21:38 UTC, Edgar-P-yan requested changes

2020-10-12 21:38 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +            this.logger.log(`No transactions`);
Ну вот в логах хер поймешь че это) Там очень много таких логов. Поэтому нужна конкретика, хотя бы название метода, допустим .log('getVotingPowerPurchaseTransactions: no transactions found')
в других местах тоже

2020-10-12 21:38 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +                transaction.txnFrom,
Это не сработает, и не сработал. Искать нужно не учитывая регистр, либо в нижнем (уже пофиксил)

2020-10-12 21:38 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase.repository.ts
> +    const userVotingPowerForLastDay = purchasesForLastDay.map(purchase => purchase.votingPower).reduce(reducer);
В таких метах не нужно самому суммировать, можно просто у базы просить готовое значение через sum("votingPower")

2020-10-12 21:38 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase.repository.ts
> +public async calculateVotingPowerForUser(userId: string): Promise<number>{
Название не совсем конкретно отображает суть метода. Нужно сказать что этот метод считает ТОЛЬКО КУПЛЕННЫЕ вотинг павер, и ТОЛЬКО за сегодня

2020-10-12 21:38 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase.repository.ts
> +    const purchasesForLastDay = await this.find({where: {createdAt: MoreThanOrEqual(memezatorContestStartTime), userId}})
memezatorContestStartTime не обычный Date объект, а Moment, это такая либа. Хз как typeorm с ним работает, может вообще не умеет с ним работать, протести плиз

2020-10-12 21:38 UTC, Edgar-P-yan commented on src/token-exchange/token-exchange.service.ts
> +import { TransactionStatus } from "../transactions/types/TransactionStatus.enum";
Этот импорт тут не нужен, ненужный код не оставляем)

2020-10-12 21:38 UTC, Edgar-P-yan commented on src/memezator/memezator.controller.ts
> +            properties: { votingPowerPurchaseAddress: { type: "string" } },
Узнай плиз как правильно это записать чтоб норм показывалось в свагере

2020-10-12 21:59 UTC, Edgar-P-yan requested changes

2020-10-12 21:59 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +                        txnFrom: transaction.txnFrom.toLowerCase(),
Чувааак, ты не записал txnId.... Без этого же никак не работает...(
Всегда нужно тестить после написания кода несколько раз и при разных условиях

2020-10-13 12:47 UTC, Edgar-P-yan requested changes

2020-10-13 12:47 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +                "getVotingPowerPurchaseTransactions",
Вот в этих местах не делай плиз вторым аргументом, а просто передавай в первом. тиоп `getVotingPowerPurchaseTransactions: ...`, потому что второй аргумент обрезается в логах и херня какая-то выходит, если посмотришь логи сервера - поймешь)

2020-10-13 12:48 UTC, Edgar-P-yan requested changes

2020-10-13 12:48 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase-cron.service.ts
> +            this.logger.log(`${transaction.id}`);
А эта?

2020-10-13 12:58 UTC, Edgar-P-yan requested changes

2020-10-13 12:58 UTC, Edgar-P-yan commented on src/memezator/voting-power-purchase.repository.ts
> +        return userVotingPowerForLastDay;
Это же объект 0_0

2020-10-13 22:12 UTC, Edgar-P-yan approved these changes

2020-10-13 22:12 UTC, merged